apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-control-plane-claim
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi