version: 0.2

phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator $AWS_IAM_AUTHENTICATOR_URL
      - curl -sS -o kubectl $KUBECTL_URL
      - curl --silent -o yq --location $YQ_URL
      - curl --silent -o jq --location $JQ_URL
      - curl --silent --location $EKSCTL_URL | tar xz -C .
      - curl --silent --location $KFCTL_URL | tar xz -C .
      - chmod +x ./kubectl ./aws-iam-authenticator ./eksctl ./yq ./jq ./kfctl
      - apt update && apt install git -y
      - export PATH=$PWD/:$PATH
  build:
    commands:
      - mkdir -p build/
      - aws eks --region $AWS_REGION update-kubeconfig --name "$CLUSTER_NAME"
      - ./kubeflow/kubeflow-uninstall.sh -c "$CLUSTER_NAME" -r $CF_OUTPUT_REGION
      - eksctl delete cluster --name "$CLUSTER_NAME" --region "$AWS_REGION"
      - aws cloudformation wait stack-delete-complete --stack-name eksctl-$CLUSTER_NAME\-cluster
      - 'if "${USE_RDS}"; then aws cloudformation delete-stack --stack-name $RDS_STACK_NAME --region $AWS_REGION; fi;'
      - 'if "${USE_RDS}"; then aws cloudformation wait stack-delete-complete --stack-name $RDS_STACK_NAME --region $AWS_REGION; fi;'
      - 'if ! "${USE_EXISTING_VPC}"; then aws cloudformation delete-stack --stack-name $INFRA_STACK_NAME --region $AWS_REGION; fi;'
      - 'if ! "${USE_EXISTING_VPC}"; then aws cloudformation wait stack-delete-complete --stack-name $INFRA_STACK_NAME --region $AWS_REGION; fi;'
      - aws cloudformation delete-stack --stack-name $STACK_NAME --region $AWS_REGION