AWSTemplateFormatVersion: 2010-09-09
Description: Amazon RDS for MySQL
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Database Instance Specifications
      Parameters:
      - DBInstanceClass
      - AllocatedStorageAndIops
    - Label:
        default: Database Options
      Parameters:
      - EngineVersion
      - MultiAZ
      - PortNumber
      - MasterUsername
      - DBSnapshotIdentifier
    - Label:
        default: Network and Security
      Parameters:
      - VpcId
      - PubliclyAccessible
      - AvailabilityZones
      - PrivateDBSubnets
      - NumberOfAvailabilityZones
    - Label:
        default: Backup
      Parameters:
      - PreferredBackupWindow
    - Label:
        default: Maintenance
      Parameters:
      - PreferredMaintenanceWindowDay
      - PreferredMaintenanceWindowStartTime
      - PreferredMaintenanceWindowEndTime
    ParameterLabels:
      MasterUsername:
        default: Master Username
      AvailabilityZones:
        default: Availability Zones
      NumberOfAvailabilityZones:
        default: Number Of Availability Zones
      MultiAZ:
        default: Multi AZ
      PortNumber:
        default: Port Number
      DBInstanceClass:
        default: DB Instance Class
      AllocatedStorageAndIops:
        default: Allocated Storage And IOPS
      EngineVersion:
        default: Engine Version
      VpcId:
        default: VPC Id
      PrivateDBSubnets:
        default: Subnets to Create DB instance
      PubliclyAccessible:
        default: Publicly Accessible
      PreferredBackupWindow:
        default: Preferred Backup Window
      PreferredMaintenanceWindowDay:
        default: Preferred Maintenance Window Day
      PreferredMaintenanceWindowStartTime:
        default: Preferred MaintenanceWindow Start Time
      PreferredMaintenanceWindowEndTime:
        default: Preferred Maintenance Window End Time
      DBSnapshotIdentifier:
        default: Amazon Resource Name (ARN) of the DB snapshot
Parameters:
  AllocatedStorageAndIops:
    Description: Storage/IOPS to allocate
    Type: String
    Default: 100GB 1000IOPS
    AllowedValues:
    - 100GB 1000IOPS
    - 300GB 3000IOPS
    - 600GB 6000IOPS
    - 1000GB 10000IOPS
  AllowMajorVersionUpgrade:
    Description: If you update the EngineVersion property to a version that's different
      from the DB instance's current major version, set this property to True.
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  AutoMinorVersionUpgrade:
    Description: Indicates that minor engine upgrades are applied automatically to
      the DB instance during the maintenance window.
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  AvailabilityZones:
    Description: list of availability zones to use, must be the same quantity as specified
      in NumberOfAvailabilityZones
    Type: List<AWS::EC2::AvailabilityZone::Name>  
  BackupRetentionPeriod:
    Description: The number of days during which automatic DB snapshots are retained.
      Setting 0 disables automatic snapshots, maximum value is 35
    Type: Number
    Default: 35
    MinValue: 0
    MaxValue: 35
  CopyTagsToSnapshot:
    Description: Indicates whether to copy all of the user-defined tags from the DB
      instance to snapshots of the DB instance.
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  DBInstanceClass:
    Description: The compute and memory capacity of the DB instance.
    Type: String
    Default: db.t3.medium
    AllowedValues:
    - db.m4.large
    - db.m4.xlarge
    - db.m4.2xlarge
    - db.m5.large
    - db.m5.xlarge
    - db.m5.2xlarge
    - db.t2.micro
    - db.t2.small
    - db.t2.medium
    - db.t2.large
    - db.t3.micro
    - db.t3.small
    - db.t3.medium
    - db.t3.large
  DBName:
    Description: The name of the database to create when the DB instance is created.
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: ^(?!^mysql$)(?!^performance_schema$)(?!^information_schema$)[a-zA-Z0-9]*$
    ConstraintDescription: must contain from 1 to 64 alphanumeric characters, and
      not be reserved mysql term.
    Default: "RDSMySQL"
  DBSnapshotIdentifier:
    Default: ''
    Description: 'Optional name or Amazon Resource Name (ARN) of the DB snapshot from which you want to restore (leave blank to create an empty database).'
    Type: String
  EngineVersion:
    Description: The version number of the database engine to use.
    Type: String
    Default: 5.7.23
    AllowedValues:
    - 5.6.41
    - 5.7.23
    - 8.0.11
  MasterUsername:
    Description: Master database Username
    Type: String
    Default: "sample"
  MonitoringInterval:
    Description: The interval, in seconds, between points when Enhanced Monitoring
      metrics are collected for the DB instance.
    Type: String
    Default: '30'
    AllowedValues:
    - '0'
    - '1'
    - '5'
    - '10'
    - '15'
    - '30'
    - '60'
  MultiAZ:
    Description: Specifies if the database instance is a multiple Availability Zone
      deployment.
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  NumberOfAvailabilityZones:
    Description: Quantity of subnets to use, if selecting more than 2 the region this
      stack is in must have at least that many Availability Zones
    Type: String
    Default: '1'
    AllowedValues:
    - '1'
    - '2'
    - '3'
  PortNumber:
    Description: The port number for the database server to listen on
    Type: Number
    Default: 3306
    MinValue: 1150
    MaxValue: 65535
  PreferredBackupWindow:
    Description: The daily time range in UTC during which automated backups are created
      (if automated backups are enabled). Cannot overlap with PreferredMaintenanceWindowTime
    Type: String
    Default: 00:00-02:00
    AllowedValues:
    - 00:00-02:00
    - 01:00-03:00
    - 02:00-04:00
    - 03:00-05:00
    - 04:00-06:00
    - 05:00-07:00
    - 06:00-08:00
    - 07:00-09:00
    - 08:00-10:00
    - 09:00-11:00
    - 10:00-12:00
    - 11:00-13:00
    - 12:00-14:00
    - 13:00-15:00
    - 14:00-16:00
    - 15:00-17:00
    - 16:00-18:00
    - 17:00-19:00
    - 18:00-20:00
    - 19:00-21:00
    - 20:00-22:00
    - 21:00-23:00
    - 22:00-24:00
  PreferredMaintenanceWindowDay:
    Description: The day of the week which RDS maintenance will be performed
    Type: String
    Default: Sun
    AllowedValues:
    - Mon
    - Tue
    - Wed
    - Thu
    - Fri
    - Sat
    - Sun
  PreferredMaintenanceWindowEndTime:
    Description: The weekly end time in UTC for the RDS maintenance window, must be
      more than PreferredMaintenanceWindowEndTime and cannot overlap with PreferredBackupWindow
    Type: String
    Default: 06:00
    AllowedValues:
    - 00:00
    - 01:00
    - 02:00
    - 03:00
    - 04:00
    - 05:00
    - 06:00
    - 07:00
    - 08:00
    - 09:00
    - '10:00'
    - '11:00'
    - '12:00'
    - '13:00'
    - '14:00'
    - '15:00'
    - '16:00'
    - '17:00'
    - '18:00'
    - '19:00'
    - '20:00'
    - '21:00'
    - '22:00'
  PreferredMaintenanceWindowStartTime:
    Description: The weekly start time in UTC for the RDS maintenance window, must
      be less than PreferredMaintenanceWindowEndTime and cannot overlap with PreferredBackupWindow
    Type: String
    Default: 04:00
    AllowedValues:
    - 00:00
    - 01:00
    - 02:00
    - 03:00
    - 04:00
    - 05:00
    - 06:00
    - 07:00
    - 08:00
    - 09:00
    - '10:00'
    - '11:00'
    - '12:00'
    - '13:00'
    - '14:00'
    - '15:00'
    - '16:00'
    - '17:00'
    - '18:00'
    - '19:00'
    - '20:00'
    - '21:00'
    - '22:00'
  PubliclyAccessible:
    Description: Indicates whether the DB instance is an Internet-facing instance.
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  StorageEncrypted:
    Description: Indicates whether the DB instance is encrypted.
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  StorageType:
    Description: Specifies the storage type to be associated with the DB instance.
    Type: String
    Default: io1
    AllowedValues:
    - io1
    - gp2
    - standard
  VpcId:
    Description: The ID of the VPC to launch the RDS instance into
    Type: AWS::EC2::VPC::Id
  PrivateDBSubnets:
    Description: The ID of the Subnets to launch the RDS instance into, Please choose Minimum of 2 subents.
    Type: List<AWS::EC2::Subnet::Id>   
Mappings:
  Version2Family:
    5.6.35:
      Family: mysql5.6
      MajorVersion: '5.6'
    5.7.23:
      Family: mysql5.7
      MajorVersion: '5.7'
Conditions:
  2az:
    !Equals
      - !Ref NumberOfAvailabilityZones
      - '2'
  3az:
    !Equals
      - !Ref NumberOfAvailabilityZones
      - '3'
  100GB:
    !Equals
    - !Ref AllocatedStorageAndIops
    - 100GB 1000IOPS
  300GB:
    !Equals
    - !Ref AllocatedStorageAndIops
    - 300GB 3000IOPS
  600GB:
    !Equals
    - !Ref AllocatedStorageAndIops
    - 600GB 6000IOPS
  1000GB:
    !Equals
    - !Ref AllocatedStorageAndIops
    - 1000GB 10000IOPS
  EncryptionEnabled:
    !Equals
    - !Ref StorageEncrypted
    - 'true'
  HasDBSnapshotIdentifier: !Not [!Equals [!Ref DBSnapshotIdentifier, '']]
Resources:
  DbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'Metadata store db secrets'
      Name: !Sub "${AWS::StackName}/RDSCredentials"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username":"${MasterUsername}"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
  DbSecretAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DbSecret
      TargetId: !Ref DBInstance
      TargetType: AWS::RDS::DBInstance
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      AllocatedStorage:
        !If
        - HasDBSnapshotIdentifier
        - !Ref 'AWS::NoValue'
        - !If
          - 100GB
          - '100'
          - !If
            - 300GB
            - '300'
            - !If
              - 600GB
              - '600'
              - !If
                - 1000GB
                - '1000'
                - '6000'
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      CopyTagsToSnapshot: !Ref CopyTagsToSnapshot
      DBInstanceClass: !Ref DBInstanceClass
      DBName: 
        !If
        - HasDBSnapshotIdentifier
        - !Ref 'AWS::NoValue'
        - !Ref DBName
      DBSnapshotIdentifier: 
        !If 
        - HasDBSnapshotIdentifier
        - !Ref DBSnapshotIdentifier
        - !Ref 'AWS::NoValue'
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: mysql
      EngineVersion: 
        !If
        - HasDBSnapshotIdentifier
        - !Ref 'AWS::NoValue'
        - !Ref EngineVersion
      Iops:
        !If
        - HasDBSnapshotIdentifier
        - !Ref 'AWS::NoValue'
        - !If
          - 100GB
          - '1000'
          - !If
            - 300GB
            - '3000'
            - !If
              - 600GB
              - '6000'
              - !If
                - 1000GB
                - '10000'
                - '60000'
      KmsKeyId:
        !If
        - EncryptionEnabled
        - !GetAtt KMSKey.Arn
        - !Ref AWS::NoValue
      LicenseModel: general-public-license
      MasterUsername: 
        !If 
        - HasDBSnapshotIdentifier
        - !Ref 'AWS::NoValue'
        - !Ref MasterUsername
      MasterUserPassword: 
        !If 
        - HasDBSnapshotIdentifier
        - !Ref 'AWS::NoValue'
        - !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:password}}']]
      MonitoringInterval: !Ref MonitoringInterval
      MonitoringRoleArn: !GetAtt MonitoringRole.Arn
      MultiAZ: !Ref MultiAZ
      OptionGroupName: !Ref DBOptionGroup
      Port: !Ref PortNumber
      PreferredBackupWindow: !Ref PreferredBackupWindow
      PreferredMaintenanceWindow: !Sub ${PreferredMaintenanceWindowDay}:${PreferredMaintenanceWindowStartTime}-${PreferredMaintenanceWindowDay}:${PreferredMaintenanceWindowEndTime}
      PubliclyAccessible: !Ref PubliclyAccessible
      StorageEncrypted: 
        !If 
        - HasDBSnapshotIdentifier
        - !Ref 'AWS::NoValue'
        - !Ref StorageEncrypted
      StorageType: 
        !If 
        - HasDBSnapshotIdentifier
        - gp2
        - !Ref StorageType
      VPCSecurityGroups:
      - !Ref RDSSecurityGroup
  DBOptionGroup:
    Type: AWS::RDS::OptionGroup
    DeletionPolicy: Retain
    Properties:
      EngineName: mysql
      MajorEngineVersion:
        !FindInMap
        - Version2Family
        - !Ref EngineVersion
        - MajorVersion
      OptionGroupDescription: !Sub Database ${DBName}
      OptionConfigurations: []
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub Database ${DBName}
      Family:
        !FindInMap
        - Version2Family
        - !Ref EngineVersion
        - Family
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub Database ${DBName}
      SubnetIds:
      - !Select
        - 0
        - !Ref PrivateDBSubnets
      - !Select
        - 1
        - !Ref PrivateDBSubnets
      - !If
        - 3az
        - !Select
          - 2
          - !Ref PrivateDBSubnets
        - !Ref AWS::NoValue
  KMSKey:
    Condition: EncryptionEnabled
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub Database ${DBName}
      Enabled: 'true'
      EnableKeyRotation: 'true'
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
        - Sid: Allow administration of the key
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action:
          - kms:Create*
          - kms:Describe*
          - kms:Enable*
          - kms:List*
          - kms:Put*
          - kms:Update*
          - kms:Revoke*
          - kms:Disable*
          - kms:Get*
          - kms:Delete*
          - kms:ScheduleKeyDeletion
          - kms:CancelKeyDeletion
          Resource: '*'
  MonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: monitoring.rds.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Allow Client connections to Database ${DBName}
      VpcId: !Ref VpcId
      #SecurityGroupIngress:
      #- IpProtocol: tcp
      #  FromPort: !Ref PortNumber
      #  ToPort: !Ref PortNumber
      #  CidrIp: !Ref VPCCidrBlock
      #SourceSecurityGroupId: !Ref EKSSecurityGroupId
      SecurityGroupEgress:
      - IpProtocol: '-1'
        FromPort: '-1'
        ToPort: '-1'
        CidrIp: 0.0.0.0/0
      Tags:
      -
        Key: "DBClusterName"
        Value: !Ref DBName
Outputs:
  EndpointAddress:
    Value: !GetAtt DBInstance.Endpoint.Address
  MasterUsername:
    Value: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:username}}']]
  MasterPassword:
    Value: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:password}}']]
  Port:
    Value: !Ref PortNumber
  DBName:
    Value: !Ref DBName
